set(_WINFSP_HINT_ROOTS)

if(DEFINED WINFSP_ROOT_DIR AND NOT "${WINFSP_ROOT_DIR}" STREQUAL "")
  list(APPEND _WINFSP_HINT_ROOTS "${WINFSP_ROOT_DIR}")
endif()

if(DEFINED ENV{WINFSP_ROOT_DIR} AND NOT "$ENV{WINFSP_ROOT_DIR}" STREQUAL "")
  list(APPEND _WINFSP_HINT_ROOTS "$ENV{WINFSP_ROOT_DIR}")
endif()

list(APPEND _WINFSP_HINT_ROOTS
  "C:/Program Files (x86)/WinFsp"
  "C:/Program Files/WinFsp"
)

set(_WINFSP_SEARCH_ROOTS)
foreach(_root IN LISTS _WINFSP_HINT_ROOTS)
  list(APPEND _WINFSP_SEARCH_ROOTS "${_root}" "${_root}/DYNAMIC")
endforeach()
list(REMOVE_DUPLICATES _WINFSP_SEARCH_ROOTS)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
    set(_WINFSP_LIBRARY_NAMES winfsp-a64)
  else()
    set(_WINFSP_LIBRARY_NAMES winfsp-x64)
  endif()
else()
  set(_WINFSP_LIBRARY_NAMES winfsp-x86)
endif()

find_path(WINFSP_INCLUDE_DIR
  NAMES winfsp/winfsp.h
  HINTS ${_WINFSP_SEARCH_ROOTS}
  PATH_SUFFIXES inc
)

find_library(WINFSP_LIBRARY
  NAMES ${_WINFSP_LIBRARY_NAMES}
  HINTS ${_WINFSP_SEARCH_ROOTS}
  PATH_SUFFIXES lib
)

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
    set(_WINFSP_RUNTIME_NAMES winfsp-a64.dll)
  else()
    set(_WINFSP_RUNTIME_NAMES winfsp-x64.dll)
  endif()
else()
  set(_WINFSP_RUNTIME_NAMES winfsp-x86.dll)
endif()

find_file(WINFSP_RUNTIME_DLL
  NAMES ${_WINFSP_RUNTIME_NAMES}
  HINTS ${_WINFSP_SEARCH_ROOTS}
  PATH_SUFFIXES bin SxS/DYNAMIC/bin
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  WinFsp
  REQUIRED_VARS WINFSP_INCLUDE_DIR WINFSP_LIBRARY
)

if(WinFsp_FOUND AND NOT TARGET WinFsp::WinFsp)
  add_library(WinFsp::WinFsp SHARED IMPORTED GLOBAL)
  set(_WINFSP_IMPORTED_PROPERTIES
    IMPORTED_IMPLIB "${WINFSP_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${WINFSP_INCLUDE_DIR}"
  )
  if(WINFSP_RUNTIME_DLL)
    list(APPEND _WINFSP_IMPORTED_PROPERTIES IMPORTED_LOCATION "${WINFSP_RUNTIME_DLL}")
  endif()
  set_target_properties(WinFsp::WinFsp PROPERTIES ${_WINFSP_IMPORTED_PROPERTIES})
endif()

mark_as_advanced(WINFSP_INCLUDE_DIR WINFSP_LIBRARY WINFSP_RUNTIME_DLL)
